txt = "hello my friends     "
x=txt.upper()
print(x)
x=txt.strip()
print(x)
print(len(txt))
x=txt.capitalize()
print(x)
x=txt.isalpha()
print(x)
x=txt.startswith("h")
print(x)
x=txt.endswith("s")
print(x)